### ISSUE TITLE
Filter and counts, maybe consider mapreduce counters

### ISSUE THREAD

**Issue by cosnicolaou** [grailbio/bigslice#18]
I've attempted to use Filter in two real world examples now but for one I had compromise on my stats reporting and for the other I had to back out of using it. I need to report the # of original inputs and the # post filtering which doesn't seem to be easily possible. I can use Scan or some other side-effect support operation, but then I need to make the side effect work across multiple machines which is annoying and expensive for something as simple as a count. Google's mapreduce offered counters which could be used for this task as this; this mechanism though seems overly general and was extensively abused so I'm not necessarily advocating for it. Given bigslice's ability to carry results through the graph via the slices themselves, maybe it makes sense to add stats to the core slice structure to report on progress through the graph - the simplest being # invocations per operation, but more detailed/extensive ones also being possible.

**Comment by mariusae** [comment]
I don't think a general stats mechanism is unreasonable. We already do publish and aggregate stats from each task (this is how e.g., the records in/out is computed). Having them follow the data flow is an interesting idea...

**Comment by cosnicolaou** [comment]
I was envisaging something along the lines of the following:
1. assign each op in the graph a name - eg. <num>.<op> where num is the order the op was encountered and <op> is the op, so for map, filter, fold you'd have 0.map, 1.filter, 2.fold
2. treat these as keys so that their stats can obtained from the session when it's complete so as to provide convenient programmatic access to them

A more general mechanism could be to provide a global singleton that each slice func could access to augment the stats maintained by the bigslice runtime. It would be a little ugly to implement since it would to walk the stack to obtain the op name etc, but certainly doable. A more traumatic change would be to provide access to the slice directly as a pseudo column (say the first or last one). That is if the func signature ends with an arg of type bigslice.Slice then provide access to the slice instance etc.

**Comment by mariusae** [comment]
Bigslice already assigns names to ops (well, tasks, which are possibly pipelined ops); but they aren't stable. I don't think we want to have coupling (in code) between the assigned names and something that, e.g., aggregates those stats in some meaningful way.

Another possibility is to just declare stats globally (like funcs) and refer to them in that way.

```
var filterCount = bigslice.NewCounter("my-filter-counter")
...

... slice = bigslice.Filter(slice, func(...) bool { filterCount.Incr(); return ... })

func main() {
    sess.Run()...
    // when done, get the total counter value:
    filterCount.Get()
}

```

**Comment by cosnicolaou** [comment]
sure, that would work too, I was assuming it would easier/cleaner to piggyback on the existing session results mechanism, but I presume you can do that just as easily with this design. Wouldn't it also be useful to make the stats that bigslice is already gathering available via the session?

**Comment by mariusae** [comment]
The main problem with piggy backing is that we have to wait until a task is complete to propagate the counter values. This seems unfortunate, especially since these sorts of metrics are useful for monitoring ongoing jobs, too.

**Comment by mariusae** [comment]
Here's a proposed design:

## Introduction

It is often useful to maintain a set of runtime statistics in
large-scale data processing jobs. These stats may include
"application" level stats, such as knowing how many records were
dropped by a filter operation, but they may also include "system"
stats like the number of database calls performed while processing a
job.

It may be useful to monitor stats in real time, but also to have an
authoritative aggregate when a job has finished.

This design proposes a stats mechanism that aims to accomodate both
of these use cases.

First, we describe the proposed API.

## Stat values

We introduce a new package, `github.com/grailbio/bigslice/stats`
that will contain the full API for declaring, publishing,
and consuming stats.

All stats are declared by a toplevel constructor.
(For now, we limit the discussion to counters.)

	var filterCount = stats.NewCounter()

The stats values themselves do not have any exported methods;
these values serve only to name a unique stat.
Instead, users can operate on stats using context-specific operators.

## Operators

Users must operate on stats using a _context_.
The context ensures that stats are recorded
and attributed correctly.

To that end, we propose to modify Bigslice
combinators funcs to request a `context.Context`
in its first argument.
For example, a `bigslice.Map` may inject a context
simply by requesting it as its first argument:

	slice = bigslice.Map(slice, func(ctx context.Context, row int) ...

The context has the type of the general 
[Go context](https://golang.org/pkg/context/)
so that we can use the same to propagate timeouts
for external operations.
This also provides a mechanism for future enhancements
without introducing further context types.

The stats package provides a set of operators that take:
a context, a stats, and a value.
For example, to increment the above count,
we may call:

	slice = bigslice.Filter(slice, func(ctx context.Context, row rowType) bool {
		if shouldKeep(row) {
			return true
		}
		stats.Incr(ctx, filterCount, 1)
		return false
	})

This design also makes it possible to 
precisely attribute stats operations;
this in turn may be useful to aggregate
these stats in different ways.

## Consuming stats

The above API allows stats to be aggregated 
and consumed in a number of ways.
First, stats may be exported for realtime monitoring.
This is done through the existing 
[expvar](https://golang.org/pkg/expvar/) mechanism
already supported by Bigmachine.
A user can export stats in their `main`:

	func main() {
		stats.Export(filterCount, "filter_count")
		...
	}

Since stats are attributed to individual operations, 
they can also flow with task outputs,
and consumed by the user after run completion.
The stats are associated with the
[Result](https://godoc.org/github.com/grailbio/bigslice/exec#Result)
returned by
[sess.Run](https://godoc.org/github.com/grailbio/bigslice/exec#Session.Run).

	func main() {
		...
		
		result, err := sess.Run(ctx, myBigsliceFunc, ...)
		...
		log.Printf("%d items filtered", result.CounterValue(filterCount))

Stats values associated with results are _precise_:
since they are derived from the precise lineage used to produce 
the returned results,
they do not include duplicates from task re-runs;
they also include stats from re-used results.

**Comment by cosnicolaou** [comment]
I think the overall design is good and it would address my needs! My only quibble is the golang context.Context is overloaded and I wonder if all of its uses would work reliable with bigslice? If I clt-c the master for instance, is that propagated to the worker nodes? I'd be very happy for that to be the case, but if it's not, then I'd argue that something other than context should be used.

**Comment by mariusae** [comment]
@cosnicolaou I don't think it's unreasonable to use a context here. We already have a context in the runtime that is tied to the task. Bigslice runs may already be canceled (e.g., by canceling the context passed into `(*Session).Run`, and this would allow us to propagate that all the way to user-supplied funcs).

**Comment by cosnicolaou** [comment]
Sounds good, propagating cancel would be a very nice feature and would allow for workers to clean up when the master is aborted. Thanks!

**Comment by cosnicolaou** [comment]
Would it be possible to create new counters dynamically from within a slice func? I would presume not given the intro, if so, please make it explicit that that's the case. Allowing dynamic creation certainly makes some things easier but introduces a significant risk of overuse. On balance, probably best to not allow dynamic creation to start with since it can always be added, but could never be taken away.

**Comment by mariusae** [comment]
> Would it be possible to create new counters dynamically from within a slice func? I would presume not given the intro, if so, please make it explicit that that's the case. Allowing dynamic creation certainly makes some things easier but introduces a significant risk of overuse. On balance, probably best to not allow dynamic creation to start with since it can always be added, but could never be taken away.

Correct. This is not allowed per this proposal, but it could be fitted in by allowing metrics to form hierarchies.

**Comment by mariusae** [comment]
This has been implemented. (At least in its initial form.)
